### ISSUE TITLE
"ERROR: You need to be running as root." on Windows

### ISSUE THREAD

**Issue by NeonNegro** [Drewsif/PiShrink#10]
when I delet  this "IF" block:
if (( EUID != 0 )); then
  echo "ERROR: You need to be running as root."
  exit -3
fi

I get the error: ERROR: parted is not installed

**Comment by Drewsif** [comment]
How are you running it on Windows? I made and tested it on Linux so that why it won't run. You can shrink it from the pi though

**Comment by NeonNegro** [comment]
Didn't know it was only for windows, sorry. Now that I know, two questions: it is possible to make a windows version one, and how can I run it from the Pi? I can't put the img inside the SD, there isn't enough space

**Comment by Drewsif** [comment]
Its possible, but I would need a windows alternative to parted and the auto resize wouldn't really work. If you have a usb hard drive you can put the image on you can use it from the pi
