### ISSUE TITLE
wlan not starting

### ISSUE THREAD

**Issue by rudiratlos** [Drewsif/PiShrink#103]
after pishrinking (latest raspbian) and transfering to a bigger SD card, pi 3b+ ist booting. look like everything is working, but wlan was not starting even with manually trying with wpa_supplicant process.

**Comment by Drewsif** [comment]
Did you restore it to the same pi or a different one?

**Comment by rudiratlos** [comment]
different one

**Comment by Drewsif** [comment]
Ah, because its a different pi it might have swapped the wifi adapters name and thats why. I've ran into that issue before. I remember deleting `/etc/udev/rules.d/70-persistent-net.rules` and that fixing it
