### ISSUE TITLE
Error showed up when running the script

### ISSUE THREAD

**Issue by Lozeonjyu** [Drewsif/PiShrink#115]
Hi,

I am trying to shrink my Rapsbian Lite copy but errors occurred when I run the script:

Below is the error when I run the script for the first time:
> pi@VMPi:~ $ sudo pishrink.sh RPT_1107tmp.img 
> pishrink.sh v0.1.2
> pishrink.sh: Gatherin data...
> Creating new /etc/rc.local
> pishrink.sh: Checking filesystem...
> root: 121693/856800 files (0.1% non-contiguous), 1169505/3425280 blocks
> resize2fs 1.43.4 (31-Jan-2017)
> pishrink.sh: Shrinking filesystem...
> resize2fs 1.43.4 (31-Jan-2017)
> Resizing the filesystem on /dev/loop0 to 1180032 (4k) blocks.
> Begin pass 2 (max = 342333)
> Relocating blocks             XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> Begin pass 3 (max = 105)
> Scanning inode table          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> Begin pass 4 (max = 9630)
> Updating inode references     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> The filesystem on /dev/loop0 is now 1179648 (4k) blocks long.
> 
> Error: You requested a partition from 1547698176B to 6381109248B (sectors 3022848..12463104).
> The closest location we can manage is 15577645056B to 15577645056B (sectors 30425088..30425088).
> pishrink.sh: ERROR occured in line 296: parted failed with rc 0

Since the second time run, the error becomes as follows:

> pi@VMPi:~ $ sudo pishrink.sh RPT_1107tmp.img 
> pishrink.sh v0.1.2
> pishrink.sh: Gatherin data...
> tune2fs: Bad magic number in super-block while trying to open /dev/loop0
> mount: /dev/loop0: can't read superblock
> md5sum: /tmp/tmp.5stYQuKCFc/etc/rc.local: No such file or directory
> Creating new /etc/rc.local
> mv: cannot stat '/tmp/tmp.5stYQuKCFc/etc/rc.local': No such file or directory
> /usr/local/bin/pishrink.sh: line 179: /tmp/tmp.5stYQuKCFc/etc/rc.local: No such file or directory
> chmod: cannot access '/tmp/tmp.5stYQuKCFc/etc/rc.local': No such file or directory
> umount: /tmp/tmp.5stYQuKCFc: not mounted
> pishrink.sh: Checking filesystem...
> e2fsck: Invalid argument while trying to open /dev/loop0
> /dev/loop0: 
> The superblock could not be read or does not describe a valid ext2/ext3/ext4
> filesystem.  If the device is valid and it really contains an ext2/ext3/ext4
> filesystem (and not swap or ufs or something else), then the superblock
> is corrupt, and you might try running e2fsck with an alternate superblock:
>     e2fsck -b 8193 <device>
>  or
>     e2fsck -b 32768 <device>
> 
> pishrink.sh: Filesystem error detected!...
> pishrink.sh: Trying to recover corrupted filesystem...
> e2fsck 1.43.4 (31-Jan-2017)
> e2fsck: Invalid argument while trying to open /dev/loop0
> 
> The superblock could not be read or does not describe a valid ext2/ext3/ext4
> filesystem.  If the device is valid and it really contains an ext2/ext3/ext4
> filesystem (and not swap or ufs or something else), then the superblock
> is corrupt, and you might try running e2fsck with an alternate superblock:
>     e2fsck -b 8193 <device>
>  or
>     e2fsck -b 32768 <device>
> 
> pishrink.sh: ERROR occured in line 58: Filesystem recoveries failed. Giving up...

Please advise if I can do anything to make it work.

Thanks

**Comment by Drewsif** [comment]
Please try again with the latest version and re-open if the issue persists. I believe this has been fixed
