### ISSUE TITLE
Not working in 8GB sized img

### ISSUE THREAD

**Issue by JayRhithu** [Drewsif/PiShrink#127]
Not working in 8GB sized img. Showing:

pishrink.sh v0.1.2
pishrink.sh: Gathering data...
Creating new /etc/rc.local
pishrink.sh: Checking filesystem...
MoodleBox_by_NMA: 124844/475200 files (0.3% non-contiguous), 1608430/1947392 blocks
resize2fs 1.44.1 (24-Mar-2018)
pishrink.sh: ERROR occured in line 269: Image already shrunk to smallest size

**Comment by Drewsif** [comment]
How much free space is left on the image? Especially on smaller images some times we can't shrink any smaller which is unfortunately out of my control since PiShrink relies on resize2fs for that
