### ISSUE TITLE
ERROR occured in line 157: parted is not installed.

### ISSUE THREAD

**Issue by Waldfeee** [Drewsif/PiShrink#140]
Hi, 
i got the Problem on my freshly installed Raspbian that pishrink fails while using it via crontab. It works fine if started manually...

pishrink.sh v0.1.2
pishrink.sh: ERROR occured in line 157: parted is not installed.

which parted gives me /sbin/parted

Any ideas?

**Comment by framps** [comment]
Set the standard pathes which also includes /sbin in your crontab definition
