### ISSUE TITLE
Add an option to reduce size without important files losses

### ISSUE THREAD

**Issue by xDaKillerx** [Drewsif/PiShrink#141]
Hi. So I have an idea . I think it'd be nice to make another option to clean logs, and useless stuff before resizing and compressing the image. That way it'll be smaller than it used to. Also idk if my logic is right or not but as far as I know. The script still keep the swap file right? Now, can we remove the file before resizing and compressing? Does the device on the boot after it's flashed will automatically make the swap file again? Or no? If not. Maybe we could make it so that it'll check the size for swap file and then zero it. So when it's compressed. It's easier and smaller. What do you think? Thanks!

**Comment by framps** [comment]
In general I think that's good idea. But I frankly think pishrink should follow the [Unix philosophy](https://de.wikipedia.org/wiki/Unix-Philosophie) 
```
Make each program do one thing well. To do a new job, build afresh rather than complicate old programs by adding new "features".
```

**Comment by xDaKillerx** [comment]
Hmm I see. Does compressing the compressed image (xz on both) will yield better compression ratio ??

**Comment by framps** [comment]
Looks like you want to shrink your image as small as possible. Frankly I don't understand this because nowadays disk space is quite cheap. But anyhow - no - I have no idea whether you will get any better compression rates because I'm fine with the standard non compressed shrinked image.

**Comment by xDaKillerx** [comment]
Okay then. Thanks for the info!! Cheers.....

**Comment by Drewsif** [comment]
Its not a bad idea but Im also trying to keep it compatible with most OS's so I wouldn't want to delete or zero files that may cause issues. I do like the idea but I don't really see it in the future.
