### ISSUE TITLE
wlan not starting form transferred SD card (rpi3B+ to rpi4)

### ISSUE THREAD

**Issue by rudiratlos** [Drewsif/PiShrink#144]
Hi,
I've flashed an SD card for my new rpi4 from my old rpi3B+
rpi4 can boot from the SD card, but didn't start the wlan connection.
My rpi3B+ can boot and connect to wlan with that sd card.
What's wrong here? Everything else is working
Thanks

**Comment by Drewsif** [comment]
This is likely an OS related issue. I'd be willing to bet that the wifi adapter has a different name in the OS now. Check if the file `/etc/udev/rules.d/70-persistent-net.rules` exists, if it does you can try to remove it and reboot. I've had that fix that issue
