### ISSUE TITLE
perfect No problem whatsoever!!!!!

### ISSUE THREAD

**Issue by linbox1968** [Drewsif/PiShrink#152]
I downloaded it and ran the command line --> No issues.

I did this on a raspberry 4 image -- The issue i had before was that I created an image with one sd card and could not copy this onto another (96MB smaller than image warning) sd card. Your script solved my issue perfect!

I tried to follow another post with parted and writing down sectors .... and it failed at the end (probably my fault)

Image was shrunk without compression in less than a  minute.

**Comment by Drewsif** [comment]
Glad to hear 😄
