### ISSUE TITLE
"pishrink.sh" does not seem to work on smb share

### ISSUE THREAD

**Issue by yuriw** [Drewsif/PiShrink#155]
File location as `/run/user/1000/gvfs/smb-share:server=pi-nas.local,share=omvbackup`

```
sudo pishrink.sh backup-omv-19-Aug-2020_10-54-34.ddfull.img
pishrink.sh v0.1.2
pishrink.sh: ERROR occured in line 216: backup-omv-19-Aug-2020_10-54-34.ddfull.img is not a file...
```

It'd be nice if it was able to work.  Pls consider.

**Comment by framps** [comment]
Please provide the output of 
```
file backup-omv-19-Aug-2020_10-54-34.ddfull.img
```

**Comment by yuriw** [comment]
@framps 

file backup-omv-19-Aug-2020_10-54-34.ddfull.img 
backup-omv-19-Aug-2020_10-54-34.ddfull.img: DOS/MBR boot sector; partition 1 : ID=0xc, start-CHS (0x40,0,1), end-CHS (0x3ff,3,32), startsector 8192, 524288 sectors; partition 2 : ID=0x83, start-CHS (0x3ff,3,32), end-CHS (0x3ff,3,32), startsector 532480, 12964041 sectors

**Comment by framps** [comment]
What's the result of following command ?

```
[[ ! -f "backup-omv-19-Aug-2020_10-54-34.ddfull.img" ]] && echo "is no file" || echo "is file"
```

**Comment by yuriw** [comment]
@framps nothing

**Comment by yuriw** [comment]
BTW it does not work when file location is /run/user/1000/gvfs/smb-share:server=pi-nas.local,share=omvbackup

After I moved it to `~/tmp` it worked fine 
FYI

**Comment by framps** [comment]
> After I moved it to `~/tmp` it worked fine

Great you tested this alternate way to use pishrink. pishrink uses the bash -f test to check if the img passed in the call is a file. For some reasons I don't know this test fails if the file is mounted via gfvs. Looks like this no pishrink issue but a gfvs issue. 

For sure I know pishrink works if the file is mounted via nfs or smb by not using gfvs. Maybe you find an alternative way to mount the image file?

**Comment by yuriw** [comment]
@framps sure makes sense, will try `fstab`

**Comment by framps** [comment]
@yuriw Do you have any update?

**Comment by yuriw** [comment]
@framps no 
I thought we said it's a limitation if the file is mounted via `gfvs`

**Comment by framps** [comment]
Ok. Then please close this issue :wink:
