### ISSUE TITLE
Add flag to force overwrite of existing file

### ISSUE THREAD

**Issue by martinkrulltott** [Drewsif/PiShrink#160]
Thanks for a great shrinking script!
I want to run this headless as part of a cron job, but if the output file already exists the scripts asks for a y/n prompt for overwriting the file 
`gzip: /media/pi/mylocation/backup.img.gz already exists; do you wish to overwrite (y or n)?`

This causes the cron job to stop execution (as no input will be provided).

Preferably this could be solved by adding a `-f` flag to enable "force overwrite".

**Comment by framps** [comment]
Why don't you delete the file first and ignore the error if it doesn' t exist?

**Comment by martinkrulltott** [comment]
Fair enough, that's actually much easier 👍
