### ISSUE TITLE
cant run pishrink

### ISSUE THREAD

**Issue by clownnut** [Drewsif/PiShrink#161]
ok, here are the command, i did.
sudo chmod +X pishrink.sh
(enter my password)
sudo ./pishrink.sh (name).img

then 
it display 
pishrink.sh v0.1.2
pishrink.sh: gathering data ... 
that's all, it froze the clock it wont do anything.
what did i do wrong?

**Comment by Drewsif** [comment]
How long did you let it run for? It can take a bit

**Comment by schmorrison** [comment]
Try running with `-v -d` options and provide the logs?
