### ISSUE TITLE
"PiShrink does not yet support autoexpanding of this type of image" - so how is it done manually?

### ISSUE THREAD

**Issue by untilted-document** [Drewsif/PiShrink#165]
PiShrink gave me that error above, but it seems seldom mentioned on the web (most hits are just to the sourcecode of the script)

Can anyone advise on the process to perform a manual expand if autoexpand is impossible?

**Comment by ymollard** [comment]
Apparently this happens when PiShrink meets a logical partition. I would say that `lvextend` can do the job but I expect it not to be sufficient, especially if there are not enough free space. `gparted` could certainly also help.
