### ISSUE TITLE
Shrink NTFS partitions of Live USB sticks with persistence

### ISSUE THREAD

**Issue by ymollard** [Drewsif/PiShrink#166]
First, many thanks, I used PiShrink sucessfully many times!

I am now trying to shrink an Ubuntu Live USB for x86-64 that has a persistent partition (NTFS). 
It looks like tune2fs can only deal with ext formats, so it fail when trying to run `tune2fs -l /dev/loop2` saying `tune2fs failed. Unable to shrink this type of image`.
I'm not expert with partitions, is it worth digging in order to add support for NTFS or is this going to be a dead end?

**Comment by Drewsif** [comment]
It should not be a dead end, but Ill make an issue for other filesystem support.  See #286
