### ISSUE TITLE
Feature request: Add -9 switch and pass it to the compression utility

### ISSUE THREAD

**Issue by elmot** [Drewsif/PiShrink#171]
-10% were gained with -9 switch to `xz`, but that drastically increases compression time.

**Comment by framps** [comment]
I frankly don't get your feature request. 

When I added the compression support I added a feature to customize the options passed to them. Just define variable PISHRINK_XZ with the options you want to pass to xz and export this variable before you call pishrink. 

See README and `Default options for compressors can be overwritten by defining PISHRINK_GZIP or PSHRINK_XZ environment variables for gzip and xz.`

**Comment by elmot** [comment]
Ah, ok. that should work. Would be nice to have that information in the help screen
