### ISSUE TITLE
pishrink.sh: /etc not found, autoexpand will not be enabled ...

### ISSUE THREAD

**Issue by WesWesthaver** [Drewsif/PiShrink#173]
I just ran pishrink.sh for the first time and saw this:

**pishrink.sh: /etc not found, autoexpand will not be enabled ...**

Can anyone tell me what this means? What can I do to correct it?

Here's the entire output:

    wes@wes-desktop:~
    $ sudo pishrink.sh /home/wes/Desktop/clone.img /home/wes/Desktop/clone2.img
    pishrink.sh v0.1.2
    pishrink.sh: Copying /home/wes/Desktop/clone.img to /home/wes/Desktop/clone2.img... ...
    pishrink.sh: Gathering data ...
    pishrink.sh: /etc not found, autoexpand will not be enabled ...
    pishrink.sh: Checking filesystem ...
    STORAGE: 26458/7135232 files (0.2% non-contiguous), 2314036/28536803 blocks
    resize2fs 1.44.1 (24-Mar-2018)
    pishrink.sh: Shrinking filesystem ...
    resize2fs 1.44.1 (24-Mar-2018)
    Resizing the filesystem on /dev/loop36 to 1541964 (1k) blocks.
    Begin pass 2 (max = 1364961)
    Relocating blocks             XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    Begin pass 3 (max = 3484)
    Scanning inode table          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    Begin pass 4 (max = 1677)
    Updating inode references     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    The filesystem on /dev/loop36 is now 1541964 (1k) blocks long.
    
    pishrink.sh: Shrinking image ...
    pishrink.sh: Shrunk /home/wes/Desktop/clone2.img from 30G to 2.0G ...

**Comment by Drewsif** [comment]
It means that the last partition in your disk image does not have a `/etc` folder. There are a few projects that use this type of setup so the auto expansion feature just wont work. You can use `raspi-config` to do it manually though
