### ISSUE TITLE
Can I run pishrink again on an already shrank image?

### ISSUE THREAD

**Issue by neilyoung** [Drewsif/PiShrink#178]
Background: It seems to me that this is problematic after several attempts. Background: I'm having a read/only fs for the PI. I shrank and zipped it with this wonderful tool (with parameter -s, in order to prevent file system expansion at startup). Then later I make some changes to that image (it can be switched to read/write by console).

My experience is, that - once I run the shrink process again on this image, it fails to boot with an error in journalctl, which points to a failing attempt to expand the file system (from which there is no return).

Any experiences here?

**Comment by Drewsif** [comment]
You should be able to shrink it again, it sounds like you didn't add the -s option again so its trying to autoexpand.
