### ISSUE TITLE
pishrink: /etc not found, autoexpand will not be enabled ...

### ISSUE THREAD

**Issue by Petengy** [Drewsif/PiShrink#182]
Error message trying to shrink PI SD Card.

OS: Ubuntu 20.04

OS on SD Card: Home Assistant OS 

How to solve it ?

By Pet

**Comment by Drewsif** [comment]
In short, you cant. PiShrink can only auto expand if the last partition in the image contains the OS. Likely this could be fixed though, but theres no short term fix
