### ISSUE TITLE
PiShrink does not shrink file

### ISSUE THREAD

**Issue by Bboy486** [Drewsif/PiShrink#183]
I have a windows share mounted on my Rpi4b.

Running 
wget https://raw.githubusercontent.com/Drewsif/PiShrink/master/pishrink.sh
chmod +x pishrink.sh
sudo mv pishrink.sh /usr/local/bin

sudo pishrink.sh /mnt/windowsnas/DenRaspberryPiBackup.img 

/mnt/windowsnas/DenRaspberryPiBackup-pishrink.img

I mounted the windows share in /mnt/windowsnas

However when running the command it doesn't shrink the file.

**Comment by Drewsif** [comment]
Can you copy paste the full console output from trying to shrink it?

**Comment by Bboy486** [comment]
> Can you copy paste the full console output from trying to shrink it?

What do I need to do to get that info to you?

**Comment by Drewsif** [comment]
Run the command and copy and paste any output here
