### ISSUE TITLE
Shrinking without resize2fs

### ISSUE THREAD

**Issue by dilyanpalauzov** [Drewsif/PiShrink#186]
PiShrink uses resize2fs to find the minimal possible size of a partition.  resize2fs is not perfect in this: for a partition of 1.7GB data and 650MB free, resize2fs does not want to shrink the 650 MB (so that the total size of the partition is 2.4GB).  To be precise, the partition was above 3GB and pishirnk made is smaller, but still there are 650 MB free “on the smallest possible partition”.

Please extend pishrink with an option to create a random directory on the host, move the content of the partition over that directory, destroy the partition, create a new partition, based on the needed size and then move the content from the random directory to the new partition.

Please add an option how much free space there shall be on the new partition, so that the system has enough space to boot.

In case the additional free space is not zeroed by default, add an option to fill the free space with zeroes, so that compressing the partition (raspberry pi image with two parfitions) creates smaller files.

**Comment by Drewsif** [comment]
The 650MB is left so that it can boot if data needs to be written on boot. The solution you mention of copying things will cause more issues than it would solve. The zeroing option has been brought up before and will be looked into
