### ISSUE TITLE
VirtualBox shared folder with Aug 2020 release or older

### ISSUE THREAD

**Issue by 2play** [Drewsif/PiShrink#189]
Just want to say thank you.
Never had a problem from shared folder in vbox.
I will test Jan release of pishrink but I believe is ok 
Fyr I'm using Linux Mint 19.1 or before that the 18.1
Both great!

**Comment by Drewsif** [comment]
Happy to hear! 👍

**Comment by positron96** [comment]
It has always worked for me as well. 

The only problem I see is that the final cleanup fails with error `xz: compressed.img: Cannot remove: Text file busy`, but the resulting file img.xz works anyway.
