### ISSUE TITLE
Using PiShrink on a Synology NAS is a charm!!

### ISSUE THREAD

**Issue by DiGiTaLAnGeL92** [Drewsif/PiShrink#19]
I had no other way to contact you and congrats about the BEAUTIFUL work you have done here!
I had a 128GB image and was struggling to find a way to resize it without having to install or virtualize a linux environment (every other script that i hitted needs gparted or dcfldd)
I discovered that my "old" Synology DS214play was perfectly capable of running it.

I had to install parted using "opkg install parted" (bootstrap is required to use opkg/ipkg) and all the other dependences were already satisfied by the fact that the NAS deals with partitions by definition, i was even able to burn the img to an sd card by dd'ing it directly to the embedded sd card reader. 
Feel free to add a note somewhere about it if you want.

I hope that i brighten your day and keep up with the cool work! Thanks again!
Marco

**Comment by Drewsif** [comment]
Thanks! I appreciate the comment and I'm really glad you found it useful :)
