### ISSUE TITLE
 extent tree (at level 2) could be narrower.  IGNORED

### ISSUE THREAD

**Issue by Haxel66** [Drewsif/PiShrink#190]
Ubuntu shrinking a retropie image.  I have had lots of success in the last few weeks but today i got this message but it still shrunk and i didnt get any errors but i am wondering if I should delete the image im working on and restore an older one as I want it to be all good. ?
pishrink.sh v0.1.2
pishrink.sh: Gathering data ...
Creating new /etc/rc.local
pishrink.sh: Checking filesystem ...
retropie: Inode 262436 extent tree (at level 2) could be narrower.  IGNORED.
retropie: Inode 262437 extent tree (at level 2) could be narrower.  IGNORED.
retropie: 217404/23088576 files (0.5% non-contiguous), 82325285/96093184 blocks
resize2fs 1.45.5 (07-Jan-2020)
pishrink.sh: Shrinking filesystem ...
resize2fs 1.45.5 (07-Jan-2020)
Resizing the filesystem on /dev/loop0 to 82633404 (4k) blocks.
Begin pass 2 (max = 137484)
Relocating blocks             XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Begin pass 3 (max = 2933)
Scanning inode table          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
The filesystem on /dev/loop0 is now 82633404 (4k) blocks long.

**Comment by Drewsif** [comment]
The image is totally fine and usable! If you want a good explanation of what the warning is you can check this post: https://unix.stackexchange.com/a/392544
