### ISSUE TITLE
Limit the number of cores when compressing

### ISSUE THREAD

**Issue by bkev** [Drewsif/PiShrink#193]
Is there any switch to limit pishrink to a certain number of cores when using compression in parallel?

I'd quite like to limit the compression to 2 cores just so it isn't running at 100% if that's possible?

Thanks for the script I think it's fantastic.

**Comment by Drewsif** [comment]
You should be able to set the enviroment variable `ZIP_PARALLEL_OPTIONS` to `-f9 -p 2` before running to limit it
