### ISSUE TITLE
Shrinking real block device /dev/sda instead of loop back device .img

### ISSUE THREAD

**Issue by rafis** [Drewsif/PiShrink#194]
Can you please an option that will allow to shrink real block device /dev/sda or /dev/mmcblk0 instead of loop back device. For example, I booted to USB Disk /dev/sda (BOOT_ORDER=0xf41) and I want to backup /dev/mmcblk0 to my USB Disk.

**Comment by Drewsif** [comment]
So the problem is that requires changing the live disk which I'm not super comfortable within the scope of this project. The changes needed would also be large enough that it could warrant its own project. 

So unfortunately, the best way is to dd the disk to your USB then pishrink. Sorry 😞
