### ISSUE TITLE
resulting img file not divisible by 512bytes

### ISSUE THREAD

**Issue by ghost** [Drewsif/PiShrink#195]
After I run pishink, the resulting img file can not be used in the Raspberry Pi Imager.  The error is that the img is not in 512 byte increments.  I can use the image in BalenaEtcher.  I guess that program is not as picky.  How do I fix this so the image works in the  Raspberry Pi Imager application?

**Comment by Drewsif** [comment]
I've never run into that issue actually. You can pad the file with anything to get it to a nice 512 byte block and that should fix it.

I'm going to leave this open to try and add it as a feature.

**Comment by tds2021** [comment]
Dumb question, how would I pad it?
