### ISSUE TITLE
e2fsck: Bad magic number in super-block 当尝试打开 /dev/loop0 时

### ISSUE THREAD

**Issue by omyhub** [Drewsif/PiShrink#196]
Skipping autoexpanding process...
pishrink.sh: Checking filesystem ...
/dev/loop0 has unsupported feature(s): metadata_csum
e2fsck: Get a newer version of e2fsck!
pishrink.sh: Filesystem error detected! ...
pishrink.sh: Trying to recover corrupted filesystem ...
e2fsck 1.42.9 (28-Dec-2013)
/dev/loop0 has unsupported feature(s): metadata_csum
e2fsck: Get a newer version of e2fsck!
pishrink.sh: Trying to recover corrupted filesystem - Phase 2 ...
e2fsck 1.42.9 (28-Dec-2013)
e2fsck: Bad magic number in super-block 当尝试打开 /dev/loop0 时

The 超级块 could not be read or does not describe a correct ext2
文件系统.  If the 设备 is valid and it really contains an ext2
文件系统 (and not swap or ufs or something else), then the 超级块
is corrupt, and you might try running e2fsck with an alternate 超级块:
    e2fsck -b 8193 <设备>

pishrink.sh: ERROR occurred in line 64: Filesystem recoveries failed. Giving up..

**Comment by Drewsif** [comment]
You need to get a newer version of `e2fsck` according to line 4 of your error.
