### ISSUE TITLE
Error after booting from shrinked image

### ISSUE THREAD

**Issue by talgreen1** [Drewsif/PiShrink#197]
I'm getting an error when booting after burning an image that I've shrinked (see below & attached file).
The same error happens on 2 different sd cards. I've tried to shrink the orig image again - same results. 
When trying to burn the orig image - no problem.
Any ideas?

10x!

The error: Give root password for maintenance (or press Control-D to continue): [133.135986] EXT4-fs error (device mmcblk0p2)
![error](https://user-images.githubusercontent.com/26517162/117776425-3c0df500-b244-11eb-8268-890b5beab260.jpg)

**Comment by Drewsif** [comment]
I need a few more bits of information

1. What OS was on the Pi?
2. How did you take the image?
3. If you put the original image back on does it work?
