### ISSUE TITLE
Shrinked with PiShrink from 120 GB SSD, then written on SD card with 32GB and expanded to same size - give me an error when i write that 32 gb im back to ssd - why?

### ISSUE THREAD

**Issue by jayjupdhig** [Drewsif/PiShrink#199]
-> https://files.slack.com/files-pri/T01JYNPBP2T-F023A1SKLH2/img_20210525_091756.jpg

Thx for feedbacks...

**Comment by jayjupdhig** [comment]
No anwser?!?

**Comment by jayjupdhig** [comment]
Ready for more??

HERE:

![IMG_20210609_093748](https://user-images.githubusercontent.com/42765391/121531653-ecffdf00-c9fe-11eb-9c5c-756e2e868e86.jpg)
![IMG_20210609_093751](https://user-images.githubusercontent.com/42765391/121531656-ed987580-c9fe-11eb-9000-0c00b031a277.jpg)
![IMG_20210608_134146](https://user-images.githubusercontent.com/42765391/121531658-ed987580-c9fe-11eb-8633-3c48be79ed69.jpg)
![IMG_20210608_134152](https://user-images.githubusercontent.com/42765391/121531661-ee310c00-c9fe-11eb-8070-419e1ac7281a.jpg)
![IMG_20210609_093006](https://user-images.githubusercontent.com/42765391/121531662-ee310c00-c9fe-11eb-950a-02e48d69f94e.jpg)
![IMG_20210609_093011](https://user-images.githubusercontent.com/42765391/121531663-ee310c00-c9fe-11eb-8513-dd37cc610ce8.jpg)

**Comment by jayjupdhig** [comment]
-> When i write the image with "HDD Raw Copy Tool 1.10", i NEVER get got a problem [because of a problematik SSD or M2 drive]... so it is realistic that the issue was caused by your script!!

**Comment by jayjupdhig** [comment]
For those who speak (or read) german:
https://forum-raspberrypi.de/forum/thread/52982-fsck-auf-raspbian-10-beim-booten-starten/?postID=494722#post494724

**Comment by Drewsif** [comment]
1. I cant click your slack link, no idea what it even is
2. This is an open source project that I do in my free time, so I'm slow to respond
3. Calm down, being a twat won't get you support from me

**Comment by jayjupdhig** [comment]
Hi. So you see, i've already closed this issue here. Thank you anyway...

**Comment by jayjupdhig** [comment]
Additional info: Slack image is here. Just for correction:
![slack_img_20210525_091756](https://user-images.githubusercontent.com/42765391/121649957-5af8e480-ca99-11eb-80cb-81d025e52b59.jpg)

**Comment by jayjupdhig** [comment]
Problem still persists...
