### ISSUE TITLE
FeatureRequest: Working with overlay file system enabled

### ISSUE THREAD

**Issue by scegg** [Drewsif/PiShrink#202]
For production creating, Overlay File System is a good way to protect sd card. But it seems that when the function is created, pishrink is not working well. Maybe the problem is about resizing a readonly file system?

**Comment by Matebo** [comment]
For me, it's stuck in a boot loop

**Comment by shatteredsword** [comment]
i would recommend that you just create the image from your sd card before enabling this option. at least until custom first boot scripting is available.

**Comment by Drewsif** [comment]
Closing for #286
