### ISSUE TITLE
ERROR occured in Line 256

### ISSUE THREAD

**Issue by Asmardos** [Drewsif/PiShrink#206]
Most probably it is my fault for trying, but I got this error as I tried to shrink an Ubuntu Image with 128 GB in size.
I used Ubuntu 20.4 in both cases. 
I executed the script on an external SSD hard drive that wasn't reachable afterwards, until I plugged it into another device.
Is there a way to shrink such an Image? 
or even better, is there a way to pipe dd directly into pishrink?
Something like:
dd if=/dev/sda5 | pishrink backup.img
and make it available for all Linux distros.
If there already exists such a thing, I would be really grateful if you inform me.
I use Linux only since a year ago, so I don't know many things.
And sorry for my bad English, I am not a native.

**Comment by Drewsif** [comment]
Im going to close this issues since its so old. If you are still having the issues please post the output from PiShrink and Ill reopen the issue.
