### ISSUE TITLE
Alternative way to resize partition

### ISSUE THREAD

**Issue by MrksKwsnck** [Drewsif/PiShrink#22]
As mentioned in [this forum](https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=148492&hilit=expand#p976727) I want to mention there is an alternative way to resize the partition on first boot, instead of touching the `/etc/rc.local` file.

You can add `init=/usr/lib/raspi-config/init_resize.sh` space separated to the end of the first line in the `/boot/cmdline.txt` file. This file resides on the boot partition and as you surely know, the boot partition has FAT32 filesystem. That script also removes the `init` statement after resizing.

I think this is the way it is meant to be.

**Comment by framps** [comment]
:+1:

**Comment by Drewsif** [comment]
The only real problem I have doing it this way is that distros without raspi-config installed wont manage to resize (See #8). I'll definitely look into it a bit more to see if it grants any advantage over just continuing to replace `/etc/rc.local`.

Thanks for the suggestion! 😄
