### ISSUE TITLE
Can it exclude a particular directory?

### ISSUE THREAD

**Issue by DRRoJohn** [Drewsif/PiShrink#222]
Hi.
I mount an HDD at root directory, let's take it as _/root/hdd_. I want to shrink whole of _/root_ andf _/boot_ except _/root/hdd_ into _/root/hdd_. Is that possible?
thank you.

**Comment by Drewsif** [comment]
It is not, PiShrink works on an entire disk image on is not directory based. It only shrinks the last partition of the disk image currently
