### ISSUE TITLE
etc not found, autoexpand will not be enabled

### ISSUE THREAD

**Issue by Jerrycatz** [Drewsif/PiShrink#226]
Console message on running pishrink on Ubuntu 20.04.3 LTS
sudo pishrink.sh picorebackup.img
pishrink.sh v0.1.2
pishrink.sh: Gathering data ...
pishrink.sh: /etc not found, autoexpand will not be enabled ...

**Comment by Drewsif** [comment]
Your root partition is likely not the last partition. It should still work as intended, you will just need to expand the last partition on your own
