### ISSUE TITLE
Shrink image with partitions

### ISSUE THREAD

**Issue by f-alemauro** [Drewsif/PiShrink#232]
Hello @Drewsif,
 thank you for this really useful script.
I have an image file created from my raspberry, but I have made a second partition. 
So in that image there are two partitions.

From the script I guess that
- only the second partition is shrunk
- as the OS is in the first partition, the script cannot exapnd the filesystem (I get the error " /etc not found, autoexpand will not be enabled ...")

Are these guesses true?

Thank you, cheers!

**Comment by Drewsif** [comment]
Correct. Only the last partition on the disk will be shrunk. It will not auto expand the disk if the last partition is not the root partition. It can still be shrunk it just needs to manually be expanded.

**Comment by f-alemauro** [comment]
Ok, thank you.

So, there's no way to auto expand a non-root partition, correct?

Talking about shrinking, if there are more than one partition, which partition get shrunk?

**Comment by Drewsif** [comment]
The last partition is the one that gets shrunk. If the last partition is the root partition then it will auto expand, if it is not it will shrink the last partition but not auto-expand it.
