### ISSUE TITLE
filesystems supported

### ISSUE THREAD

**Issue by matthiesenj** [Drewsif/PiShrink#233]
I think you should explicitly list in the documentation which filesystems are supported - many people use f2fs on their Pi's these days (including me) and it would be nice not having to go down a rabbit hole and hit a dead end with this when it could have easily been avoided.

**Comment by framps** [comment]
I think it would be even better to add some code which checks whether pishrink supports the image passed in. In your case it would make sense to add a check for ext4 on the second partition. Just mount the image on a loop device and check the partitioning.
