### ISSUE TITLE
pishrink.sh: ERROR occurred in line 216: pi.img is not a file...

### ISSUE THREAD

**Issue by nituladaboneko** [Drewsif/PiShrink#239]
pi@raspberrypi:/usr/local/bin $ sudo pishrink.sh pi.img
pishrink.sh v0.1.2
pishrink.sh: ERROR occurred in line 216: pi.img is not a file...

**Comment by jfitzpat** [comment]
I got exactly the same error.

**Comment by framps** [comment]
What's the result of 
```
la -la pi.img?
```

**Comment by framps** [comment]
Hm ... according [this description](https://stackoverflow.com/a/10204597/1742425) 

```
-f file
              True if file exists and is a regular file.

A regular file is something that isn't a directory, symlink, socket, device, etc.
```

you shouldn't get the error message :confused:

**Comment by jfitzpat** [comment]
It is very peculiar. The image in on a mounted thumb drive. I tried gzip, then reloaded it on another SD card with the PI Imager - nothing weird about the image. I've also used successfully used pishrink.sh before...

**Comment by shatteredsword** [comment]
pishrink doesn't work correctly if run directly on an external drive. you'll need to copy the file over to your filesystem and then back again once you've shrank the file.

**Comment by BigBobDalton** [comment]
I get the same error.  No, its not on a external drive.

**Comment by Drewsif** [comment]
Try giving the full path to the file instead of a relative path. If there are spaces in the path be sure to put it in quotes
