### ISSUE TITLE
rootfs: Inode 772 extent tree (at level 1) could be shorter.  IGNORED.

### ISSUE THREAD

**Issue by The-Exterminator** [Drewsif/PiShrink#241]
How can i fix this error : rootfs: Inode 772 extent tree (at level 1) could be shorter.  IGNORED. ???
i only get this error with Raspberry Bullseye 32bit.
Raspberry Bullseye 64bit and Raspberry Buster 32bit give not the error.

**Comment by Drewsif** [comment]
Looks like there was a filesystem problem. Did it shink fine?

**Comment by The-Exterminator** [comment]
Yes is do
I have try many times, and the error come Hole time

**Comment by Drewsif** [comment]
Can you post the full output of the script please?

**Comment by ValeZAA** [comment]
It is very simple. Boot with Gparted, open Terminal and run

e2fsck -f /dev/sda1

And it will ask you that inode, press y.
