### ISSUE TITLE
Add better detection of existing /etc/rc.local changes

### ISSUE THREAD

**Issue by Drewsif** [Drewsif/PiShrink#258]
Currently PiShrink uses `md5sum` to detect if we have already changed `/etc/rc.local`. This is extremely fragile and not the best choice.

The new method should:
1. Allow for the expansion script to be edited without having to update anything else in the script.
2. Detect if a PiShrink expansion script is already present in the image and overwrite it with it's own version.
    - In this case the backup made of `/etc/rc.local` should not be touched  

My initial idea for a new method is to put a unique string into the expansion script which we key on.

**Comment by Sniffleupagus** [comment]
How about "if /etc/rc.local.bak already exists, don't overwrite it". Overwrite rc.local all you want, but keep the original backup to be eventually restored.
