### ISSUE TITLE
ERROR occurred in line 300: tune2fs failed. Unable to shrink this type of image.

### ISSUE THREAD

**Issue by gismc123** [Drewsif/PiShrink#264]
I am using the Le Potato in lieu of the Raspberry Pi because they are too expensive these days. On the AML-S905X-CC "Le Potato", i am running Raspbian OS (https://distro.libre.computer/ci/raspbian/11/) which can be downloaded from their official distro list for supported OS's. I have customized the install so that I can create an image and deploy it to several other le potatos (i am hoping to make a cluster with 6 potatos). Anyway, I tried to use the PiShrink to make the image smaller but I got the error on the title of this post. I am not sure if this is a bug or if there is something different with the image that i used link: https://distro.libre.computer/ci/raspbian/11/2022-09-22-raspbian-bullseye-arm64%2Baml-s905x-cc.img.xz. 

Here is the command line output. 

`username@LePotato-Node2:/media/username/NAS/1tb $ sudo dd if=/dev/mmcblk1 of=/media/username/NAS/1tb/Le_Potato_06.18.23.img bs=4M status=progress
30932992000 bytes (31 GB, 29 GiB) copied, 1969 s, 15.7 MB/s
7378+0 records in
7378+0 records out
30945574912 bytes (31 GB, 29 GiB) copied, 1969.93 s, 15.7 MB/s
username@LePotato-Node2:/media/username/NAS/1tb $ sudo pishrink.sh /media/username/NAS/1tb/Le_Potato_06.18.23.img /media/username/NAS/1tb/Le_Potato_06.18.23-shrink.img
pishrink.sh v0.1.3
pishrink.sh: Copying /media/username/NAS/1tb/Le_Potato_06.18.23.img to /media/username/NAS/1tb/Le_Potato_06.18.23-shrink.img... ...
pishrink.sh: Gathering data ...
tune2fs: Bad magic number in super-block while trying to open /dev/loop0
tune2fs 1.46.2 (28-Feb-2021)
/dev/loop0 contains a btrfs file system labelled 'rootfs'
pishrink.sh: ERROR occurred in line 300: tune2fs failed. Unable to shrink this type of image
username@LePotato-Node2:/media/username/NAS/1tb $
`

**Comment by Drewsif** [comment]
It is not a bug, your rootfs is btrfs which PiShrink does not currently support. So unfortunately until that gets added you can't shrink that image.
