### ISSUE TITLE
File System not expanding 

### ISSUE THREAD

**Issue by arjunkahlon** [Drewsif/PiShrink#267]
Hi,

Thanks for this utility. I'm having an issue where the file system is not expanding after booting the cloned image. The Root Partition is the size of the cloned image and I'm left with a large chunk of unallocated space. I  noticed that rc.local is not being created. I'm currently closing Manjaro which I run on a Raspberry Pi.

**Comment by strooooke** [comment]
The solution in https://github.com/Drewsif/PiShrink/issues/151 worked for me (different image, not even targeting a RasPi, but an Olimex - but still).

**Comment by strooooke** [comment]
Sadly, the solution in 0.1.4 does not. No autoexpanding happening.
