### ISSUE TITLE
possibility to add costum scripts to the new iso?

### ISSUE THREAD

**Issue by murph12F** [Drewsif/PiShrink#268]
is there any way to add some custom script that will be exucuted by the iso once booted? would be a dope feature, btw super cool tool thank you!

**Comment by Drewsif** [comment]
I think this would fall under #256. It's not exactly cleanup but could be used in the same way I think. So in short, currently there is not, but maybe in the future! For now I would just pre-prepare the image with what you want it to do on boot before shutting it down.

Glad you are enjoying the tool 😄
