### ISSUE TITLE
pishrink writes to stderr instead of stdout

### ISSUE THREAD

**Issue by firewiremb** [Drewsif/PiShrink#273]
Pishrink writes “normal progress messages” to stderr instead of stdout:

```
pishrink.sh v0.1.3
pishrink.sh: Copy from /home/pi/USB_Stick1/raspi-live-roh.img to /home/pi/USB_Stick1/raspi-live.img... ...
```

When used in crontab without >/dev/null, an email is sent reporting an error which does not exist. Therefore &>/dev/null must be used. This means that real error messages cannot be sent by email.

**Comment by Drewsif** [comment]
I just ran a test and I only get 2 lines on stderr both of which are `resize2fs 1.47.0 (5-Feb-2023)` which is not from PiShrink directly. Checking the exit code is your best bet to see if PiShrink failed or not, the utilities may output to stderr but we at no point do. You could also run the script with `2>&1` at the end and see if that silences it.
