### ISSUE TITLE
new shrink image is not running.

### ISSUE THREAD

**Issue by jasvinder1079** [Drewsif/PiShrink#274]
I clone a sd card of 16gb into a image and then shrunk it into small image of 4.5 gb from 14-15 gb .Now with balena Etcher during flashing i'm getting this error "something went wrong. if it is a compressed image, please check that the archive is not corrupted".

**Comment by Drewsif** [comment]
Are you trying to use a gziped pishrink image? Can you share the command line you used?

**Comment by jasvinder1079** [comment]
Hi @Drewsif ,
I finally able to flash the rpi image into a memory card with balena etcher and its working .
Now my question is will this image work on CM4 if we flash it into emmc?

**Comment by Drewsif** [comment]
I don't see why not! But I have never tried
