### ISSUE TITLE
parted: invalid token: primary

### ISSUE THREAD

**Issue by WaJoWi** [Drewsif/PiShrink#28]
I only back up a partition from an SSD (sda2) to an img file on a FAT32 partition with 'dd if=/dev/sda2 of=/media/fat32/file.img bs=1M'. This works flawlessly.

Then I start: 'sudo /usr/local/bin/pishrink. sh /media/fat32/file.img'

There I get the following output until the script gets stuck with the error:

```
Creating new /etc/rc.local
e2fsck 1.43.3 (04-Sep-2016)
Durchgang 1: Inodes, Blöcke und Größen werden geprüft
Durchgang 2: Verzeichnisstruktur wird geprüft
Durchgang 3: Verzeichnisverknüpfungen werden geprüft
Durchgang 4: Referenzzähler werden überprüft
Durchgang 5: Zusammengefasste Gruppeninformation wird geprüft
/dev/loop0: 76785/229440 Dateien (0.3% nicht zusammenhängend), 587124/971264 Blöcke
resize2fs 1.43.3 (04-Sep-2016)
resize2fs 1.43.3 (04-Sep-2016)
Die Größe des Dateisystems auf /dev/loop0 wird auf 754009 (4k) Blöcke geändert.
Start von Durchgang 2 (max = 46859)
Blöcke werden verschoben     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Start von Durchgang 3 (max = 30)
Die Inode-Tabelle wird gelesenXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Das Dateisystem auf /dev/loop0 is nun 753664 (4k) Blöcke lang.

parted: invalid token: primary
```

What's wrong here?

**Comment by Drewsif** [comment]
PiShrink expects a full disk image, not just a partition. Try making your image with `dd if=/dev/sda of=/media/fat32/file.img bs=1M` and see if that works

**Comment by WaJoWi** [comment]
Too bad, because I can't use pishrink with it. Finally, I want to make the backup to the same SSD in a separate partition. So only the partitions 'boot' and 'system'.

pishrink also failed when I backed up only the blocks of the first two partitions from the SSD.

Can't you change this to shrink images of individual partitions?
