### ISSUE TITLE
[Tip/Idea]: Make Releases to check if update is necessary

### ISSUE THREAD

**Issue by hasenradball** [Drewsif/PiShrink#280]
Hi,

I would recommend to make releases to be able to check for a new version.
And shortly describe what has changed.
It is very easy to setup.

kind regards
Frank

**Comment by Drewsif** [comment]
Good suggestion, I'll start using the release feature and look into having the script check for updates 😄

**Comment by Drewsif** [comment]
Also please head over to https://github.com/Drewsif/PiShrink/discussions/285 and vote if you get a few
