### ISSUE TITLE
Add Support for "Bookworm" and Later Releases

### ISSUE THREAD

**Issue by bbrown-spsu** [Drewsif/PiShrink#287]
The boot partition is 512 MiB on Bookworm and the mechanism for expanding the file system has changed, possible because the boot code is running from RAMdisk.  Is it possible to check the OS version and handle Bookworm, and presumably later releases correctly?

**Comment by bbrown-spsu** [comment]
My problem was caused by a software mismatch that was my fault.

**Comment by Drewsif** [comment]
All good! Thanks for the update
