### ISSUE TITLE
latest pishrink script (version="v0.1.5") caused hard disk to fill up completely

### ISSUE THREAD

**Issue by cmtao** [Drewsif/PiShrink#288]
I downloaded and ran pishrink (version="v0.1.5") to compress my img file and before I knew it, my entire 1.8TB hard disk was filled to the brim by a file in the root directory (filename: PiShrink_zero_file) and almost crashed my system. Fortunately, I was able to discover this file, delete it and bring my system up again.

**Comment by Drewsif** [comment]
How large was your image? It's supposed to zero the disk but it should not go outside the disk limit.

**Comment by Drewsif** [comment]
Should be fixed in the new version!
