### ISSUE TITLE
Pishrink doesn't shrink BookWorm image file

### ISSUE THREAD

**Issue by Docteur-No** [Drewsif/PiShrink#299]
I wanted to shrink a bookworm 64bits image which is on a USB key (µSD). Using Pishrink under Bookworm or Buster OS result is the same.

### Here is the result :

`phil@PhilBox64:/media/phil/9286-4DB0 $ sudo pishrink.sh -d philbox.img
pishrink.sh: Creating log file /media/phil/9286-4DB0/pishrink.log
PiShrink v24.10.23 - https://github.com/Drewsif/PiShrink

pishrink.sh: Gathering data
pishrink.sh: Checking filesystem
rootfs: 281729/942080 files (0.2% non-contiguous), 3359370/3757440 blocks
resize2fs 1.47.0 (5-Feb-2023)
pishrink.sh: Filesystem already shrunk to smallest size. Skipping filesystem shrinking
pishrink.sh: Shrunk toto.img from 15G to 15G
`
### Here is the pishrink.log :

`PiShrink v24.10.23 - https://github.com/Drewsif/PiShrink

pishrink.sh: Gathering data
Line 326
beforesize: 15G
parted_output: BYT;
/media/pi/3C700FBE700F7E40/philbox.img:15931539456B:file:512:512:msdos::;
1:5242880B:407896063B:402653184B:fat32::lba;
2:413138944B:15803613183B:15390474240B:ext4::;
partnum: 2
partstart: 413138944
parttype: primary
tune2fs_output: tune2fs 1.44.5 (15-Dec-2018)
Filesystem volume name:   rootfs
Last mounted on:          /
Filesystem UUID:          803b81d5-c5d1-45d4-b0bf-3adef6d7e66d
Filesystem magic number:  0xEF53
Filesystem revision #:    1 (dynamic)
Filesystem features:      has_journal ext_attr resize_inode dir_index filetype needs_recovery extent flex_bg sparse_super large_file dir_nlink extra_isize metadata_csum
Filesystem flags:         unsigned_directory_hash 
Default mount options:    user_xattr acl
Filesystem state:         clean
Errors behavior:          Continue
Filesystem OS type:       Linux
Inode count:              942080
Block count:              3757440
Reserved block count:     187871
Free blocks:              368899
Free inodes:              660086
First block:              0
Block size:               4096
Fragment size:            4096
Reserved GDT blocks:      878
Blocks per group:         32768
Fragments per group:      32768
Inodes per group:         8192
Inode blocks per group:   512
Flex block group size:    16
Filesystem created:       Tue Oct 22 15:28:19 2024
Last mount time:          Tue Nov 19 18:17:01 2024
Last write time:          Sun Nov 24 17:51:08 2024
Mount count:              28
Maximum mount count:      -1
Last checked:             Tue Oct 22 15:28:19 2024
Check interval:           0 (<none>)
Lifetime writes:          20 GB
Reserved blocks uid:      0 (user root)
Reserved blocks gid:      0 (group root)
First inode:              11
Inode size:	          256
Required extra isize:     32
Desired extra isize:      32
Journal inode:            8
Default directory hash:   half_md4
Directory Hash Seed:      a71d4884-b13f-463f-bb3a-1e3c3586b3ee
Journal backup:           inode blocks
Checksum type:            crc32c
Checksum:                 0x5b90a781
currentsize: 3757440
blocksize: 4096
Creating new /etc/rc.local
pishrink.sh: Checking filesystem
rootfs: 281997/942080 files (0.2% non-contiguous), 3388544/3757440 blocks
resize2fs 1.44.5 (15-Dec-2018)
Line 346
currentsize: 3757440
minsize: 3757440
pishrink.sh: Filesystem already shrunk to smallest size. Skipping filesystem shrinking
Line 453
aftersize: 15G
pishrink.sh: Shrunk philbox.img from 15G to 15G
`

What is wrong ?

**Comment by Drewsif** [comment]
This is because `resize2fs` can not shrink the filesystem anymore than it already is and there is nothing more we can do. I've seen this before and I'm not 100% sure why as there is generally free disk space but it is out of my hands.

You can try messing with `resize2fs` to see if there is some option combination to get it working but check the free space and make sure you are not using most/all of the 15G. If you find something do let me know and sorry I could not have an answer to fix it.
