### ISSUE TITLE
Error if path contains blank spaces

### ISSUE THREAD

**Issue by Haretuerk** [Drewsif/PiShrink#30]
If path to image contains blank spaces the script won't find the image correctly.

**Comment by framps** [comment]
I fixed this issue and created a [PR](https://github.com/Drewsif/PiShrink/pull/31). Please try [this modified version](https://github.com/Drewsif/PiShrink/blob/4af698457e32cffe39a7b5f1c85bdd8050b11823/pishrink.sh)
