### ISSUE TITLE
Error from tune2fs when running in docker only

### ISSUE THREAD

**Issue by barjonas** [Drewsif/PiShrink#300]
I'm using a docker image created from this:

```
FROM debian:bookworm

RUN apt update && apt install -y wget parted gzip pigz xz-utils udev e2fsprogs && apt clean

# Setup Env
ENV LANG=C.UTF-8
ENV TERM=xterm-256color
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /workdir

ADD https://raw.githubusercontent.com/Drewsif/PiShrink/master/pishrink.sh /usr/local/bin/pishrink
RUN chmod +x /usr/local/bin/pishrink

ENTRYPOINT ["/bin/bash"]
```

I get an interactive shell into it using this:
`docker run -it -v /myImageDir:/workdir pishrink`

Then I run `pishrink -sZa /workdir/myImage.img`

I've tried on images from multiple RPi cards created by Win32Imager. Each time I get:

```
PiShrink v24.10.23 - https://github.com/Drewsif/PiShrink

pishrink: Gathering data
losetup: cannot find an unused loop device
tune2fs: No such file or directory while trying to open
Couldn't find valid filesystem superblock.
tune2fs 1.47.0 (5-Feb-2023)
pishrink: ERROR occurred in line 319: tune2fs failed. Unable to shrink this type of image
```

Running on a different machine using Debian on WSL2, everything works just fine on the same images with the same pishrink.sh.

**Comment by Drewsif** [comment]
If you would like to use docker you can follow the MacOS instructions here https://github.com/Drewsif/PiShrink?tab=readme-ov-file#macos-instructions. Just ignore the Mac specific stuff and use the docker file and command listed there. You needed to add `--privileged=true` which is why the loopback failed.
