### ISSUE TITLE
inode errors force me to press Y to fix

### ISSUE THREAD

**Issue by tobyweston** [Drewsif/PiShrink#33]
I'm not sure why I seem to have **a lot** of errors against my image when running PiShrink.

I'll get a lot of errors:

```
inode 139115 has compression flag set on filesystem without compression support. Clear<y>? 
inode 139115 has INDEX FL flag set but its not a directory. Clear HTree index<y>?
```

The trouble is it feels like all the inodes are broken so I keep pressing `Y` and it moves onto the next one.

So two questions really, is my image fubar'ed / have I done something so wrong, it's a doomed exercise? and 2) is there an option I can pass through to what ever is doing the check to default my action to `Y`? (I've left a weight on the keyboard for now!)

Thanks

**Comment by Drewsif** [comment]
The newest version should stop some of these errors. If you're image is too far gone you'll need to say yes to things manually. You can run `yes | sudo ./pishrink img.img` and it will answer yes for you automatically.

**Comment by tobyweston** [comment]
Thanks 👍
