### ISSUE TITLE
installing pishrink?

### ISSUE THREAD

**Issue by John-Mc** [Drewsif/PiShrink#36]
sorry to bother you with something so basic, but how do I install PiShrink on my RPi3? (running Raspian Stretch)

**Comment by framps** [comment]
Execute following commands in a command window :smiley: :
```
wget https://raw.githubusercontent.com/Drewsif/PiShrink/master/pishrink.sh
chmod +x pishrink.sh
sudo mv pishrink.sh /usr/local/bin
```
Now invoke `pishrink.sh`

**Comment by John-Mc** [comment]
Thanks, @framps   I've been away from the Pi for a while, and am just getting back in to poking around with it again. Surprising how much I've forgotten

**Comment by John-Mc** [comment]
Might be worth putting the install directions in the readme for the rest of us noobs?
