### ISSUE TITLE
README.md typo?

### ISSUE THREAD

**Issue by John-Mc** [Drewsif/PiShrink#37]
The usage example in your README.md file reads:
`Usage: ./pishrink [-s] imagefile.img [newimagefile.img]`

Should it read:
`Usage: ./pishrink.sh [-s] imagefile.img [newimagefile.img]`
(note added .sh)

Also, should the first line of your example read:
`... sudo ./pishrink.sh pi.img`
(note added "pi" before shrink)

**Comment by Drewsif** [comment]
You're right, let me fix that

**Comment by Drewsif** [comment]
Closed by 5a89ff4262cf5c30813045c204c8900627329547
