### ISSUE TITLE
Fix for Partition alignment

### ISSUE THREAD

**Issue by Hamak72** [Drewsif/PiShrink#45]
Hello there
This pishrink script saved my day :-)
I use minibian and create my images with win32diskimager
I got this warning:
Warning: The resulting partition is not properly aligned for best performance
that was fixed by adding -a minimal on line 167, like this:
part2=`parted -a minimal "$img" unit B mkpart primary $partstart $newpartend`

it did not work with optimal

Thank you, this is amazing :-)

**Comment by Drewsif** [comment]
Thanks for the suggestion. I tested the change and it didn't seem to break anything for my test image. 

Closed by eac933beb8a7e02f1d45f5cd24fd09919ec97713
