### ISSUE TITLE
pishrink hangs up, if parted waits for interaction

### ISSUE THREAD

**Issue by kle99** [Drewsif/PiShrink#46]
pishrink hangs up, if an imagefile is corrupt. Why? parted tries to interact with the user. 

You can run parted, without user intervention:
`man parted`
`       -s, --script`
`                never prompts for user intervention`

--- screenshot 1 -- pishrink with corrupt image
`./pishrink2.sh /mnt/usb/corrupt.img /mnt/usb/corrupt-shrink.img`
`Copying /mnt/usb/corrupt.img to /mnt/usb/corrupt-shrink.img...`
`Error: Can't have a partition outside the disk!`
`^C`                          <=== interaction, I aborted pishrink with Ctrl-C / Strg-C

--- screenshot 2 -- parted with corrupt image
`parted -m /mnt/usb/pishrink/corrupt-shrink.img unit B print`
`Error: Can't have a partition outside the disk!`
`Ignore/Cancel? Cancel`                               <=== interaction, I entered "Cancel"
`BYT;`
`/mnt/usb/corrupt-shrink.img:4021420032B:file:512:512:unknown::;`

--- screenshot 3 -- parted ... with option '-s'
`parted -s -m /mnt/ntfs/corrupt-shrink.img unit B print`
`Error: Can't have a partition outside the disk!`
`BYT;`
`/mnt/ntfs/corrupt-shrink.img:4021420032B:file:512:512:unknown::;`

**Comment by Drewsif** [comment]
This should have gotten fixed in #40. Thanks for reporting the issue!
