### ISSUE TITLE
pishrink with corrupt image fails after 10 minutes copying.

### ISSUE THREAD

**Issue by kle99** [Drewsif/PiShrink#48]
my command:    pishrink  'imagefile'   'newimagefile'
in this case, pishrink copies the imagefile and than runs parted.
I have a corrupt imagefile.  Linux command cp doesn't recognize a problem. 
Copying takes 10 minutes on a RPi 3B.  After copying, Linux parted runs in an error.

I would prefer running parted checking the imagefile before copying the image.

**Comment by Drewsif** [comment]
The parted commands change the image, so it would be counter productive to the whole goal of having to copy it. I also feel the frustration from having to wait on the copy and I'm trying to come up with ways to make it faster if I can.
