### ISSUE TITLE
confusing multiple error messages

### ISSUE THREAD

**Issue by kle99** [Drewsif/PiShrink#50]
Command: ./pishrink.sh "corrupt_image" "newimagefile"
parted fails with "Error: Can't have a partition outside the disk!" but pishrink continues with additional errors.
Sorry for missing leading spaces in consol output. The code tag eats them.

`root@raspberrypi5:~# ./pishrink.sh /mnt/ntfs/pishrink/2018-02-06-jessie-3.2-waveshare-peppy--2016-11-08-pitft-35r.img /mnt/ntfs/pishrink/2018-02-06-jessie-3.2-waveshare-peppy--2016-11-08-pitft-35r-pishrink.img`
`Copying /mnt/ntfs/pishrink/2018-02-06-jessie-3.2-waveshare-peppy--2016-11-08-pitft-35r.img to /mnt/ntfs/pishrink/2018-02-06-jessie-3.2-waveshare-peppy--2016-11-08-pitft-35r-pishrink.img...`
`Error: Can't have a partition outside the disk!`
`tune2fs: Invalid argument while trying to open /dev/loop2`
`Couldn't find valid filesystem superblock.`
`mount: wrong fs type, bad option, bad superblock on /dev/loop2,`
`       missing codepage or helper program, or other error`

`       In some cases useful info is found in syslog - try`
`       dmesg | tail or so.`
`md5sum: /tmp/tmp.AysbwzUb5G/etc/rc.local: No such file or directory`
`./pishrink.sh: line 69: [: !=: unary operator expected`
`umount: /tmp/tmp.AysbwzUb5G: not mounted`
`e2fsck: Invalid argument while trying to open /dev/loop2`
`/dev/loop2:`
`The superblock could not be read or does not describe a valid ext2/ext3/ext4`
`filesystem.  If the device is valid and it really contains an ext2/ext3/ext4`
`filesystem (and not swap or ufs or something else), then the superblock`
`is corrupt, and you might try running e2fsck with an alternate superblock:`
`    e2fsck -b 8193 <device>`
` or`
`    e2fsck -b 32768 <device>`

`resize2fs 1.42.12 (29-Aug-2014)`
`resize2fs: Invalid argument while trying to open /dev/loop2`
`./pishrink.sh: line 142: [[: Couldn'tfindvalidfilesystemsuperblock.: syntax error: invalid arithmetic operator (error token is "'tfindvalidfilesystemsuperblock.")`
`./pishrink.sh: line 148: - Couldn'tfindvalidfilesystemsuperblock.: syntax error: invalid arithmetic operator (error token is "'tfindvalidfilesystemsuperblock.")`
`resize2fs 1.42.12 (29-Aug-2014)`
`resize2fs: Invalid argument while trying to open /dev/loop2`
`Couldn't find valid filesystem superblock.`
`ERROR: resize2fs failed...`
`mount: wrong fs type, bad option, bad superblock on /dev/loop2,`
`       missing codepage or helper program, or other error`

`       In some cases useful info is found in syslog - try`
`       dmesg | tail or so.`
`mv: cannot stat ‘/tmp/tmp.AysbwzUb5G/etc/rc.local.bak’: No such file or directory`
`umount: /tmp/tmp.AysbwzUb5G: not mounted`

**Comment by Drewsif** [comment]
Closed with #129
