### ISSUE TITLE
Loop device remains open on error and abort

### ISSUE THREAD

**Issue by kmbach** [Drewsif/PiShrink#54]
If pishrink does not leave properly, the loop device remains open. Memory is blocked until the loop device is deleted. A trap handler could solve this Problem.

function cleanup() {
    losetup -d "$loopback"
}

trap cleanup SIGINT SIGTERM EXIT 

Please check and implement if necessary.

**Comment by framps** [comment]
@kmbach I like your proposal and modified pishrink in [url=https://github.com/framps/PiShrink/blob/master/pishrink.sh]my fork[/url]. Please test whether it's working as expected. If yes, let me know and I will create a PR.

**Comment by kmbach** [comment]
Hi, framp, I provokad a 'ERROR: Image already shrunk to smalllest size'
And as expected - the loop drive was deleted.
