### ISSUE TITLE
this script not support kali

### ISSUE THREAD

**Issue by rqh656418510** [Drewsif/PiShrink#64]
Does the script not support Kali for RaspberryPi? I shrink Kali image, but not success.

**Comment by framps** [comment]
Why do you think PiShrink doesn't support Kali? I guess you get some error messages when using PiShrink with a Kali image. Why don't you share your execution log but state PiShrink fails with Kali :unamused:

**Comment by Drewsif** [comment]
Gonna close this for inactivity. If you post the execution log I'll look into it!
