### ISSUE TITLE
Not an Issue just advice on getting pishrink to work

### ISSUE THREAD

**Issue by soslug** [Drewsif/PiShrink#66]
From the outset I would like to credit the author of this script and thank them / him / her whichever is applicable.  

If you are already running Linux and " Debian stretch" in particular you DO NOT need any virtual box or similar application, it will work straight from the command line, provided a few dependencies are met, that you are root or sudo, and that the file has been made executable. I would advise the latest build of this script and you have at least three times the space of the file you are trying to compress.  

Dependencies 

On the command line in a terminal run this command

which parted losetup tune2fs md5sum e2fsck resize2fs

you should see something similar to this
/sbin/parted
/sbin/losetup
/sbin/tune2fs
/usr/bin/md5sum
/sbin/e2fsck
/sbin/resize2fs

Most linux builds support these applications but if after you run the script and the image fails for whatever reason it not because of dependencies, if you have the above you can use apt-cache search to find and install these apps if they are missing most unlikely though.

Running the script.
As in the Manual you have be given an example of how to use the script pishrink.sh, if you have made your own image let say then you have already expanded the file system to it's maximum and therefore you DO NOT need switch "s" or "-s". I had my own troubles getting this script to work, but managed eventually.

1. Ensure you have the latest version of pishrink.sh (from command line 
git clone https://github.com/Drewsif/PiShrink.git)
or if you already have a copy then select github folder with pishrink locally on your computer and ("git pull")
2. In the command line change your directory to that of pishrink in my case
(/home/derek/Downloads/linux-tools/pi_shrink) ok I admit it I changed the folder name.
3. Modify the permissions of the file and make executable
(chmod +x filename.sh) or to be specific in my case (chmod +x pishrink.sh) you do not need to be root or super user.
4. Run the script without using "-s" option in my case it was sudo ~/Downloads/linux-tools/pi_shrink/pishrink.sh a_modified_raspberry_build.img which might be 16Gb in size for example this would compress down to something more manageable for storage and re imaging purposes. Also in the Manual well README it is suggested you run the command + Original.img + Newshrink.img this should work please remember though if you have expanded your filesystem DO NOT use either of the above with "-s"

I hope this insight is of help I was doing it the long way for ever this script takes all the pain away and a lot easier. Feel free to comment below I will try and help if you still have issues. If you are using windows machines and virtualization tools then sorry I can't help you if you are running linux on a laptop or Pc then I will try and be of help.

**Comment by Drewsif** [comment]
Thanks for the post! I've added some more details into the README, hopefully making it a bit more clear over time. I'm always open to suggestions
