### ISSUE TITLE
Shrinking dual boot image

### ISSUE THREAD

**Issue by amilino** [Drewsif/PiShrink#70]
Hi,
first of all, thank you for this script, I've been using it for my RPI and it is working perfectly.

Yesterday I tried to use it on my laptop. I have Jumper book, where I installed on internal eMMC card Windows 10 and Kubuntu 18.04 in dual boot. I did backup of entire device (mmcblk1) with dd command, and did shrinking of it. During the process I received some messages that something is wrong and I was offered to chose "y" for fixing it. At the end when I try to mount img I get error and when I examine img file I see that GPT partition is damaged. As far as I can see only Kubunut partition was shrinked. So I guess I cannot use this script if I have GPT partitions in my image file? Is it possible to enhance code in script and simply skip shrinking of not supported partitions? I would like to use this script on my laptop also not just on my RPI.

Thank you in advance for the answer.

All best,
amilino

**Comment by Drewsif** [comment]
It should fail faster and safer now on partitions that it can not shrink
