### ISSUE TITLE
After shrink there is still unwanted free space in the shrunk .img file

### ISSUE THREAD

**Issue by slappymcphee** [Drewsif/PiShrink#71]
So we have an odd situation for some unknown reason where after shrinking a 7.4GB backed up .img file we are left with a 7.1GB image file that has for some reason 1.6GB of free space "stuck". We have attempted to defrag the crud out of it however for some reason that just does not help. Not really understanding why the end marker is not moving to the end of the data stored?

Here is a visual representation by mounting the image after burning back to an SD card without auto expansion enabled:

[https://cdn.discordapp.com/attachments/387702892733399062/477650973909712907/unknown.png](url)

Here is the output when running the script:

```
creating new /etc/rc.local
rootfs: 165359/483328 files (0.1% non-contiguous), 1472248/1907328 blocks
resize2fs 1.42.13 (17-May-2015)
resize2fs 1.42.13 (17-May-2015)
Resizing the filesystem on /dev/loop0 to 1825047 (4k) blocks.
Begin pass 2 (max = 43333)
Relocating blocks             XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Begin pass 3 (max = 59)
Scanning inode table          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
The filesystem on /dev/loop0 is now 1825047 (4k) blocks long.

Shrunk XU4-V2-Base-4.4.1.4-BETA.img from 7.5G to 7.1G
```

**Comment by Drewsif** [comment]
It looks like theres something thats preventing `resize2fs` from making the image any smaller. You could try running `e2fsck` to see if theres something odd happening?
