### ISSUE TITLE
Raspbian not completely booting after pishrink

### ISSUE THREAD

**Issue by marcert** [Drewsif/PiShrink#73]
Hi,
i created a new imagefile from raspbian (all updates installed) with rpi-clone and tested it. Works.
Then I tried to shrink it with PiShrink (file was then around 5G) wrote this to the SD.
If I now try to boot with this SD-Card I see the 4 Raspberries, then the splash screen and then no graphical UI.
I can also ssh to the Raspberry and see that e.g. the lightdm process is running but I do not get the normal UI via HDMI and also not via xrdp.
Has somebody an idea what happens there? What can I do to change that behavior?

Thanks and Kind Regards,
Marco

**Comment by sealyau** [comment]
what services as listed as failed when you run "systemctl --state=failed"

**Comment by Drewsif** [comment]
Closing stale issue, feel free to re-open with more details

**Comment by davidzfr** [comment]
Hi, I've the same problem.
Raspbian 12 desktop 32 bits.
No GUI, no access to desktop on the screen.
Only an underscore blinking at the top left corner of the screen.
I can access to the Rpi through ssh.
The config.txt is exactly the same.
Any Idea ?
