### ISSUE TITLE
/dev/root does not exist or is not a symlink

### ISSUE THREAD

**Issue by AlfaBravoX** [Drewsif/PiShrink#81]
When using raspi-config to again resize filesystem after using this script, it cannot be done: 
**/dev/root does not exist or is not a symlink. Don't know how to expand .** 
Creating link manually does not help either. 

SD card is size 16G
df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       7.2G  6.3G  594M  92% /
devtmpfs        460M     0  460M   0% /dev
tmpfs           464M     0  464M   0% /dev/shm
tmpfs           464M  7.4M  457M   2% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           464M     0  464M   0% /sys/fs/cgroup
/dev/mmcblk0p1   56M   23M   34M  40% /boot
tmpfs            93M     0   93M   0% /run/user/1002

any idea?

**Comment by Drewsif** [comment]
What distro are you using?

**Comment by AlfaBravoX** [comment]
Raspbian 
cat /etc/debian_version
9.4
uname -a 4.9.64-v7+ #1053 SMP Tue Nov 21 14:56:27 GMT 2017 armv7l GNU/Linux

**Comment by AlfaBravoX** [comment]
OK i resized partition by fdisk manually, then resize2fs /dev/mmcblk0p2 and it looks good:
 df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        15G  6.3G  7.3G  47% /

not sure if this relates to the script, the error message of raspi-config still persists

**Comment by Drewsif** [comment]
I will look into it

**Comment by Drewsif** [comment]
Closing for now as I've not been able to reproduce and have made a ton of changes since. If the newest version of PiShrink is giving you an issue please re-open this
