### ISSUE TITLE
PiShrink and Virtual Box 5.2.22

### ISSUE THREAD

**Issue by blackestberry** [Drewsif/PiShrink#83]
I know this is a specific issue but PiShrink seems to be often used with VirtualBox.
Would it be possible to write a tutorial how to get to run PiShrink in a shared folder with the latest Virtual Box version?
There seem to be problems since about one year. I do not know enough about all this stuff to say that only Oracle can solve the problem.

I know that this is a specific problem, but PiShrink seems to be commonly used with VirtualBox.
Is it possible to get a tutorial on how to run PiShrink in a shared folder with the latest Virtual Box version?
There seem to be problems for about a year. It would be great if you could handle the mistakes of Oracle (GuestAddition...?!, loopX Input/Output fail).

https://www.virtualbox.org/ticket/17360?cversion=0&cnum_hist=1#comment:8

**Comment by Drewsif** [comment]
The problem is with VirtualBox. I can try to add a tutorial in the readme but VirtualBox is just bad and it makes me sad
