### ISSUE TITLE
Typeo in README.md

### ISSUE THREAD

**Issue by sealyau** [Drewsif/PiShrink#87]
Evening mate,
Just ran over the readme file to make a few changes, the main fix was raspian to raspbian up-to you if you would like to run with them.

Regards

PiShrink

PiShrink is a bash script that automatically shrinks a Raspberry Pi image file  for storage. When the image is written back to an SD card it will then resize to the max size of the SD card on boot. This will dramatically decrease the time taken to write the image back onto the SD. The shrunk image file will far less storage space.
Usage

sudo pishrink.sh [-s] imagefile.img [newimagefile.img]

If the -s option is given the script will skip the auto-expanding part of the process. If you specify the newimagefile.img parameter, the script will make a copy of imagefile.img then shrink the new file. You will need enough space to make a full copy of the image to use that option.
Prerequisites

If you are trying to shrink a NOOBS image it will likely fail. This is due to NOOBS paritioning being significantly different than **Raspbian's**. Hopefully PiShrink will be able to support NOOBS in the near future.

If using Ubuntu, you will likely see an error about e2fsck being out of date and metadata_csum. The simplest fix for this is to use Ubuntu 16.10 and up, as it will save you a lot of hassle in the long run.
Installation

wget https://raw.githubusercontent.com/Drewsif/PiShrink/master/pishrink.sh
chmod +x pishrink.sh
sudo mv pishrink.sh /usr/local/bin

Example

[user@localhost PiShrink]$ sudo pishrink.sh pi.img
e2fsck 1.42.9 (28-Dec-2013)
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
/dev/loop1: 88262/1929536 files (0.2% non-contiguous), 842728/7717632 blocks
resize2fs 1.42.9 (28-Dec-2013)
resize2fs 1.42.9 (28-Dec-2013)
Resizing the filesystem on /dev/loop1 to 773603 (4k) blocks.
Begin pass 2 (max = 100387)
Relocating blocks             XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Begin pass 3 (max = 236)
Scanning inode table          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Begin pass 4 (max = 7348)
Updating inode references     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
The filesystem on /dev/loop1 is now 773603 blocks long.

Shrunk pi.img from 30G to 3.1G

Contributing

If you find a bug please create an issue for it. If you would like a new feature added, you can create an issue for it but I can't promise that I will get to it.

Pull requests for new features and bug fixes are more than welcome!

**Comment by Drewsif** [comment]
Thanks for pointing that out! I didn't see any other changes in yours, feel free to point out if I did.

You can also feel free to pull request readme changes to make it a bit easier to see the changes
