### ISSUE TITLE
Order of execution

### ISSUE THREAD

**Issue by theronic** [Drewsif/PiShrink#96]
When should I run this? Do I need to run this on Raspbian from the SD card itself? Do I make an image first, then put the image on my laptop and run it from OSX?

Secondly, would it be possible to run this on the Pi to be imaged and shrunk itself, then write a compressed version of itself to its own free space? That would be very useful for backups.

**Comment by John-Mc** [comment]
PiShrink runs on Linux systems; it wont run from OSX. You can run it from a Pi sunning Raspian, once you have installed it. PiShrink does need an IMG file to start with, so you can't just shrink your SD card directly. There are commands to make an IMG file from your SD card while booted from it on your Pi, but if you are running OSX, I'd recommend Apple Pi Baker: you run it on your Mac to make an IMG file from an SD card, or to restore and IMG file to an SD card.

I'm not sure there is a much point storing the shrunken file on the SD card the image came from. If there is a problem with the card, you risk having a problem with your backup as well. I plug a USB flash drive into my pi and store the output there.
